"""Add permissions and client_id

Revision ID: 5ee76b180b43
Revises: ec1917816d45
Create Date: 2026-08-31 20:02:50.280530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee76b180b43'
down_revision: Union[str, Sequence[str], None] = 'ec1917816d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=True)
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.add_column('identity_credential', sa.Column('client_id', sa.String(), nullable=False))
    op.add_column('identity_credential', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_identity_credential_client_id'), 'identity_credential', ['client_id'], unique=True)
    op.add_column('workload_identity', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workload_identity', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workload_identity', type_='foreignkey')
    op.drop_column('workload_identity', 'role_id')
    op.drop_index(op.f('ix_identity_credential_client_id'), table_name='identity_credential')
    op.drop_column('identity_credential', 'expires_at')
    op.drop_column('identity_credential', 'client_id')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
