"""Add performance indexes

Revision ID: 70786eefac98
Revises: 19706ca2faf3
Create Date: 2026-08-31 22:46:50.849586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70786eefac98'
down_revision: Union[str, Sequence[str], None] = '19706ca2faf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_approval_request_status'), 'approval_request', ['status'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)

    op.create_index(op.f('ix_security_event_timestamp'), 'security_event', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_event_timestamp'), table_name='security_event')

    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_approval_request_status'), table_name='approval_request')
    # ### end Alembic commands ###
