"""Add anomaly_score

Revision ID: 8b6842a34b83
Revises: 5ee76b180b43
Create Date: 2026-08-31 22:03:14.219547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6842a34b83'
down_revision: Union[str, Sequence[str], None] = '5ee76b180b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('anomaly_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'anomaly_score')
    # ### end Alembic commands ###
